### ISSUE TITLE
Encountered a PSR-4 autoloading error

### ISSUE THREAD

**Issue by divineniiquaye** [leafsphp/leafMVC#11] opened 2021-11-22 07:48 UTC
# Description

The current folder structure is problematic for development, especially as it's borrowed from [Laravel](https://github.com/laravel/laravel) but not done right. I wonder why the database folder is found in the application's folder, as it violates the PSR-4 autoloading standard.

Here's a screenshot of the problem so you:
![image of error](https://user-images.githubusercontent.com/53147395/142819928-b7f8feac-9eef-4e76-b635-fd7a90568ee9.png)

# Expected Behavior or Solution

I expect that the whole folder architecture is restructured to be unique, and not a look-alike of something else.

**Comment by mychidarko** [comment] 2021-11-22 10:15
Hi @divineniiquaye, thanks for pointing out the directory structure problem. This was caused by a bunch of typos which have been fixed now. Leaf MVC, Leaf API and Skeleton originally had a mix of uppercase and lowercase folder names which didn't really appeal to me since day one.

<img width="419" alt="image" src="https://user-images.githubusercontent.com/26604242/142842676-1aaefd09-6204-4730-8bc0-36c27db5a059.png">

Actually, the directory structure is a mix of both Laravel and [Ruby on Rails](), but the idea here was to have only one folder holding the main development files, which happens to be the `app` folder. In this case, you don't have your project files scattered in a bunch of directories. That's the motivation.

**Comment by mychidarko** [comment] 2021-11-22 19:20
This has also been rectified as of now. You can wait for the preview version or install the v3.x branch now.

**Closed as completed by mychidarko** 2021-11-22 19:20 UTC
